# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Black.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Black.proto',
  package='dbc',
  serialized_pb='\n\x0b\x42lack.proto\x12\x03\x64\x62\x63\"6\n\nBlackTable\x12\r\n\x05tname\x18\x01 \x01(\t\x12\x19\n\x05tlist\x18\x02 \x03(\x0b\x32\n.dbc.Black\"O\n\x05\x42lack\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\r\n\x05UseID\x18\x02 \x01(\x03\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0f\n\x07\x45ndTime\x18\x04 \x01(\x05\x12\x0c\n\x04Type\x18\x05 \x01(\x05')




_BLACKTABLE = _descriptor.Descriptor(
  name='BlackTable',
  full_name='dbc.BlackTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tname', full_name='dbc.BlackTable.tname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tlist', full_name='dbc.BlackTable.tlist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=74,
)


_BLACK = _descriptor.Descriptor(
  name='Black',
  full_name='dbc.Black',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='dbc.Black.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UseID', full_name='dbc.Black.UseID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Name', full_name='dbc.Black.Name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EndTime', full_name='dbc.Black.EndTime', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Type', full_name='dbc.Black.Type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=155,
)

_BLACKTABLE.fields_by_name['tlist'].message_type = _BLACK
DESCRIPTOR.message_types_by_name['BlackTable'] = _BLACKTABLE
DESCRIPTOR.message_types_by_name['Black'] = _BLACK

class BlackTable(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLACKTABLE

  # @@protoc_insertion_point(class_scope:dbc.BlackTable)

class Black(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLACK

  # @@protoc_insertion_point(class_scope:dbc.Black)


# @@protoc_insertion_point(module_scope)
