# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Walfare.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Walfare.proto',
  package='dbc',
  serialized_pb='\n\rWalfare.proto\x12\x03\x64\x62\x63\":\n\x0cWalfareTable\x12\r\n\x05tname\x18\x01 \x01(\t\x12\x1b\n\x05tlist\x18\x02 \x03(\x0b\x32\x0c.dbc.Walfare\"a\n\x07Walfare\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x11\n\tStartTime\x18\x02 \x01(\x05\x12\x0e\n\x06UserID\x18\x03 \x01(\x03\x12\x0c\n\x04Type\x18\x04 \x01(\x05\x12\x0b\n\x03Num\x18\x05 \x01(\x05\x12\x0c\n\x04\x44\x65sc\x18\x06 \x01(\t')




_WALFARETABLE = _descriptor.Descriptor(
  name='WalfareTable',
  full_name='dbc.WalfareTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tname', full_name='dbc.WalfareTable.tname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tlist', full_name='dbc.WalfareTable.tlist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=80,
)


_WALFARE = _descriptor.Descriptor(
  name='Walfare',
  full_name='dbc.Walfare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='dbc.Walfare.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartTime', full_name='dbc.Walfare.StartTime', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserID', full_name='dbc.Walfare.UserID', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Type', full_name='dbc.Walfare.Type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Num', full_name='dbc.Walfare.Num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Desc', full_name='dbc.Walfare.Desc', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=179,
)

_WALFARETABLE.fields_by_name['tlist'].message_type = _WALFARE
DESCRIPTOR.message_types_by_name['WalfareTable'] = _WALFARETABLE
DESCRIPTOR.message_types_by_name['Walfare'] = _WALFARE

class WalfareTable(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WALFARETABLE

  # @@protoc_insertion_point(class_scope:dbc.WalfareTable)

class Walfare(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WALFARE

  # @@protoc_insertion_point(class_scope:dbc.Walfare)


# @@protoc_insertion_point(module_scope)
