//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protofiles/commdef.proto
namespace commdef
{
    [global::ProtoBuf.ProtoContract(Name=@"SexType")]
    public enum SexType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"female", Value=0)]
      female = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"male", Value=1)]
      male = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LeaderboardType")]
    public enum LeaderboardType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"none_board", Value=0)]
      none_board = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"battle_power", Value=1)]
      battle_power = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"region_level", Value=2)]
      region_level = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SkillTrigType")]
    public enum SkillTrigType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"buff", Value=0)]
      buff = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"debuff", Value=1)]
      debuff = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SkillType")]
    public enum SkillType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"none", Value=0)]
      none = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"sword", Value=1)]
      sword = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"fist", Value=2)]
      fist = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"knife", Value=3)]
      knife = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"talent", Value=10)]
      talent = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"pet", Value=11)]
      pet = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QTE", Value=12)]
      QTE = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"zhengwu", Value=13)]
      zhengwu = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"moster", Value=14)]
      moster = 14
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SkillTargetType")]
    public enum SkillTargetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enemy", Value=0)]
      enemy = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"self", Value=1)]
      self = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"selfAndTeammate", Value=2)]
      selfAndTeammate = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SkillSlot")]
    public enum SkillSlot
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"noramlAtk", Value=0)]
      noramlAtk = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"skill1", Value=1)]
      skill1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"skill2", Value=2)]
      skill2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"skill3", Value=3)]
      skill3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"weapon", Value=4)]
      weapon = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"zhengwuslot", Value=5)]
      zhengwuslot = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Rules")]
    public enum Rules
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Limitation_PlayerLevel", Value=0)]
      Limitation_PlayerLevel = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Limitation_ColdDown", Value=1)]
      Limitation_ColdDown = 1
    }
  
}